### ISSUE TITLE
Result vs try-catch

### ISSUE THREAD

**Issue by smatsuodev** [smatsuodev/webserv-old#1]
Rust風にResult型を使うか`try-catch`でハンドルするかどっちにする？
決め手は関数のエラーハンドリングを呼び出し側に強制させるかどうか。

### パターンマッチが言語レベルでない
- マクロなどで擬似的に代用可能かも
- Resultは２値しか取らないので、`if (result.is_ok())`などで代用もできる
- Resultからint型への型変換を実装すれば、switchにも組み込めそう

### 型がDRYじゃない（draft）
Result型はテンプレートクラスで実装できるが、愚直に実装すると`Result<T, E>`型の派生クラスは型引数のうち、片方しか情報を持たなくなる。
```c++
Result<int, string> r = new Ok<int>(0);
```
しかし、これは`Ok<int>`には`Result<T, E>`のうち、Eの型がわからないため`Result<int, string>`にマッチしない。
よって、正しく実装するにはOkクラスを`Ok<T, E>`として実装する必要がある。

**Comment by smatsuodev** [comment]
色々調べたけど厳しそう

**Comment by smatsuodev** [comment]
動的例外指定で良き
https://learn.microsoft.com/ja-jp/cpp/cpp/exception-specifications-throw-cpp?view=msvc-170

**Comment by harsssh** [comment]
try-catch嫌いなので、`Result<T>`を使いませんか？~~エラーの値は重要じゃないので、stringでも何でもいい。~~
エラーの種類分からないと困るか. うーん.

**Comment by harsssh** [comment]
Resultが欲しい理由
- 戻り値でエラーハンドリングすることに慣れてる
- システムコールが例外を投げないので、エラー発生時に自分で例外を投げることになる。どの例外を投げるか(あるいは独自に定義するか)を考えたくない
- noexceptが使えないので、今は廃止になっている動的例外仕様を使わざるを得ない
- throwを書かないと例外を投げるのかどうか、ソースを読まないとわからない。読みたくない。
- かといってthrowをいちいち書きたくない
