### ISSUE TITLE
TRYマクロでErrの型さえ合っていればコンパイルできるようにする方法を調査する

### ISSUE THREAD

**Issue by harsssh** [smatsuodev/webserv-old#104]
# 概要
TRYマクロでErrの型さえ合っていればコンパイルできるようにする方法を調査する

# 背景
#65 の見積もりができなかった

# AC（受け入れ条件）
- TRYマクロの修正方針をまとめる

# タイムボックス
2 days

# TODO
- [ ] 調査
- [ ] 共有

**Comment by smatsuodev** [comment]
ErrかNoneだった時にreturnする式を`types::convertToNoneOrErr(expr)`みたいなのにして、`types::convertToNoneOrErr(e)`はテンプレート型で引数がResult型がOption型かで返す値を変えればいけそう

**Comment by harsssh** [comment]
`types::convertToNoneOrErr(e)` は `Result -> Err` または `Option -> None` のテンプレート関数にする必要がありますが、いけますかね。

**Comment by smatsuodev** [comment]
さっき手元で試した感じはいけそうです。
普通に戻り値はオーバーロードし放題な気がしています。
