### ISSUE TITLE
Requestクラスの設計

### ISSUE THREAD

**Issue by smatsuodev** [smatsuodev/webserv-old#5]
WebフレームワークにありがちなHTTPリクエストを表現するクラスを作る

**Comment by smatsuodev** [comment]
未対応部分
- [ ] curlからChunked Requestを送った場合
- [ ] telnetの場合、リクエストが1行ずつ送られてきて、EOFとかでリクエストの終了を判別できないので、既存のReadFileでは対応不可

**Comment by harsssh** [comment]
Goでchunked transfer encodingされたリクエストを読み込む実装例
https://baubaubau.hatenablog.com/entry/2017/11/19/133212

**Comment by harsssh** [comment]
ヘッダーの終わりは空行です。
Bodyの終わりはContent-Lengthヘッダーで判断できそうです。(ない場合はどうなるんだろう)
