### ISSUE TITLE
カバレッジの計測を導入したい

### ISSUE THREAD

**Issue by harsssh** [smatsuodev/webserv-old#55]
# 実現したいこと

カバレッジの計測を導入したい. なぜなら PBI の DONE の定義がテストの pass であり, テストの品質がプロダクトの質に直結するからだ.
ただし, カバレッジはコードの最低限の品質を担保するものであることに注意.

# AC（受け入れ条件）

- PR ごとにカバレッジの変化を確認できる
- いつでも一目でカバレッジを確認できるようにする (README にバッジを表示するとか)

# TODO

- [x] sercetにCODECOV_TOKENを追加 @EringiShimeji 
- [x] workflowを修正 
  - [x] テストを実行するworkflowにCodecovのワークアラウンドを追加 @harsssh 
  - [x] READMEにバッジを追加 @EringiShimeji 
  - [x] レビュー
  - [x] マージ
- [x] PRでカバレッジの変化が見れるか確認 @EringiShimeji

**Comment by smatsuodev** [comment]
カバレッジについて
https://tech.nri-net.com/entry/coverage_c0_c1_c2_mcc

**Comment by smatsuodev** [comment]
カバレッジの計測方法
- gcovの使い方（https://www.ois-yokohama.co.jp/oisblog2018/archives/6664）
- バッジの貼り方（https://qiita.com/tomoten/items/8e7c7551765be30b5dc6#4-github-actions%E3%81%AEci%E3%81%A7%E3%82%AB%E3%83%90%E3%83%AC%E3%83%83%E3%82%B8%E6%83%85%E5%A0%B1%E5%8F%96%E5%BE%97）

**Comment by smatsuodev** [comment]
みれました

![Image](https://github.com/EringiShimeji/webserv/assets/59910028/36fa46cb-fd5f-4f37-b71c-8b90bee81a2d)
