### ISSUE TITLE
echo serverを実装するモブプロをしたい

### ISSUE THREAD

**Issue by harsssh** [smatsuodev/webserv-old#58]
# 実現したいこと

echo serverを実装するモブプロをしたい, なぜなら課題の前提知識やアーキテクチャに対する理解を高められるからだ.
webserv の骨組みを作る目的もある.

# AC（受け入れ条件）

目的を達成するため, 以下の要件を満たすことが望ましい.

- echo server が正しく動作すること
- ファイルは適切にディレクトリ分けする
- `accept`, `read`, `write` はそれぞれ別のクラスが行う
    - つまり, `IOTask` を介してそれぞれの操作をしてほしい
    - `write` する内容の生成 (今回は `read` した内容と同じ) は `Handler` みたいなクラスに切り出せるとより良い
- Contextクラスのインターフェースだけ決めてコードにする

# タイムボックス
1day

# TODO

- [x] CLionのCode with meのセッションを作る
- [x] サーバーソケットをlistenする
- [x] 接続をacceptする
- [x] リクエストを読み込む
- [x] レスポンスを生成する
- [x] レスポンスを書く
- [x] レビュー
- [x] マージ

# メモ
リモートでやります

**Comment by smatsuodev** [comment]
> 目的を達成するため, 以下の要件を満たすことが望ましい.
> 
> - ファイルは適切にディレクトリ分けする
> - `accept`, `read`, `write` はそれぞれ別のクラスが行う
>     - つまり, `IOTask` を介してそれぞれの操作をしてほしい
>     - `write` する内容の生成 (今回は `read` した内容と同じ) は `Handler` みたいなクラスに切り出せるとより良い

ここら辺はACかも

**Comment by smatsuodev** [comment]
あとシンプルにecho serverが動くこととか。

ACは「このPBI、もうやらなくていいや」って判断できる条件と考えていいと思う

**Comment by harsssh** [comment]
lint が厳しくて辛かったので、設定を変えるPRを作った。
#69
