### ISSUE TITLE
カバレッジについて調べる

### ISSUE THREAD

**Issue by smatsuodev** [smatsuodev/webserv-old#74]
# 概要
- GTestでカバレッジを計測する方法を調べる
- カバレッジの種類について適切なものを選定する

# タイムボックス
1day

**Comment by harsssh** [comment]
~~C1 カバレッジを使うのが良さそう. 一定の網羅性を担保できて、テスト作成の負担を抑えられる。~~
`gcov` を使うと C0, C1 両方出るっぽい。

**Comment by harsssh** [comment]
参考になりそう: https://qiita.com/iydmsk/items/0021d1ef14660184f396
